### ISSUE TITLE
show Changelog in RPM-info view

### ISSUE THREAD

**Issue by sperrholz** [ImmobilienScout24/yum-repo-server#64]
It would be great if changelog could be displayed directly, so users won't have to download the RPMs to inspect them.

**Comment by oli99sc** [comment]
Should not be to much of a problem, as data seems to be available in underlying data structure. Lets see...

**Comment by oli99sc** [comment]
Works now with the same logic as files, that is you have to click the changelog heading to make changelog visible.

**Comment by sperrholz** [comment]
Thank you very much for the quick response and implementation. I hope I'll be able to update+test this soon.
