### ISSUE TITLE
RPMs are downloaded from WebUI as f.txt

### ISSUE THREAD

**Issue by alivespirit** [ImmobilienScout24/yum-repo-server#70]
Hi,
We have found an issue with the latest version compiled from sources from github. Any RPM is downloaded from web interface with the name `f.txt`. Wget or curl downloads everything correctly (if without `--content-disposition` option).
We are using now an old version (not sure from which revision, but without "delete" option for RPMs in WebUI), which doesn't have this issue, but we want to upgrade.
Java 1.8.0_60, Tomcat 8.0.12.

Also, another thing (not a big deal) is with constructing links: when you go to `http://<yum.server.url>/<repo>` without slash in the end, links on the page are pointing to `http://<yum.server.url>/noarch` etc, but should point to `http://<yum.server.url>/<repo>/noarch` (missing `<repo>`, and so url gives 404).

**Comment by heroldus** [comment]
Hi @alivespirit,

thx for the bug report. I can confirm that this is an using. We do not download RPMs much, that's why we didn't notice the behavior. I will deep dive later, today....

**Comment by alivespirit** [comment]
Thanks a lot, @heroldus!
